Repository hydrogram/hydrogram, pull requests merged in 2024-06, with the labels that each got.

#34 Move dev tools scripts to a separate folder and add a raw API docs scraper + docs.json
  cherry-pick-pyro.sh
  compiler/api/docs.json
  dev_tools/cherry_pick_pyro.py
  dev_tools/generate_docs_json.py
  pyproject.toml
Labels: documentation, enhancement

#35 Many improvements to the compiler
  .pre-commit-config.yaml
  compiler/api/compiler.py
  compiler/docs/compiler.py
  compiler/errors/compiler.py
  pyproject.toml
Labels: enhancement

#33 Add ChatBackground type and fix.
  compiler/docs/compiler.py
  hydrogram/types/user_and_chats/__init__.py
  hydrogram/types/user_and_chats/chat.py
  hydrogram/types/user_and_chats/chat_background.py
Labels: enhancement

#36 doc(migration-guide): update migration guide to reflect latest changes
  docs/source/start/migration-guide.rst
Labels: documentation

#7 docs: Refactor Hydrogram vs Pyrogram page
  docs/source/hydrogram-vs-pyrogram.rst
Labels: documentation

#37 doc(news): add missing news entries
  news/+emoji.removal.rst
  news/+misc.misc.rst
  news/+sync.removal.rst
  news/14.bugfix.rst
  news/14.misc.rst
  news/21.bugfix.rst
  news/25.bugfix.rst
  news/32.feature.rst
  news/33.feature.rst
  news/34.doc.rst
Labels: documentation
